### ISSUE TITLE
Petrolette installable in a sub domain?

### ISSUE THREAD

**Issue by beanface42** [YunoHost-Apps/petrolette_ynh#12]
### Describe the request

*Proposing an option for installing Petrolette in a sub-path*

### Context

- Raspberry Pi at home
- YunoHost version: 4.2.6.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *yes*

### Enhancement request

Would it be possible to have an option to install the Yunohost Petrolette into a subdirectory, like for my example:

https://anancus.ynh.fr/petrolette

and have it work from there? 

My knowledge in Nginx is far too basic to have a clue about the way to do this manually.

Thank you in advance for the feedback.

**Comment by oiseauroch** [comment]
I can't do it now because the upstream app doesn't allow to do it. There is an upstream open issue : https://framagit.org/yphil/petrolette/-/issues/50
request to assets are hard coded so that nginx can't redirect properly the request

**Comment by oiseauroch** [comment]
New version accept sub domain
