### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/petrolette_ynh#9]
Hello,
Today there was a possible update for petrolette
So I launched this one via the webadmin but it did not succeed and worse it could not even restore the version saved pre-upgrade ..
Here is the copy of the log..
https://paste.yunohost.org/raw/okijifuqul

**Comment by oiseauroch** [comment]
Hello, thanks for the reports. I fixed this error on the install script but forgot to do the same on the update and restore script. It should be fixed now (versior 1.3.5~ynh3).
Petrolette doesn't store anything locally (everything is stored on the web browser so you can safely install petrolette again and you should keep your feed selection
